name: movilizate
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_cache_manager: ^3.4.1
  flutter_map: ^8.1.1
  flutter_svg: ^2.0.17
  geolocator: ^13.0.4
  go_router: ^14.8.1
  google_nav_bar: ^5.0.7
  latlong2: ^0.9.0
  line_icons: ^2.0.3
  permission_handler: ^11.4.0
  supabase_flutter: ^2.3.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
